-- AlterTable
ALTER TABLE "users" ADD COLUMN     "dailyAdCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "lastAdDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "patinhasLite" INTEGER NOT NULL DEFAULT 0;
